name: "Build & Test"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, mongodb
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "MongoDB is up!" && exit 0
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB did not start in time" && exit 1

      - name: Run PHPUnit
        env:
          MONGODB_URI: "mongodb://localhost:27017/?serverSelectionTimeoutMS=100"
          MONGODB_DATABASE: "mongoquila"
        run: vendor/bin/phpunit
